services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ROOT_PASSWORD: securepassword
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_user_pass
    volumes:
    - wordpress:/var/www/html
    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  wordpress:
  db:
